name: Lint Markdown

on: pull_request

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install --global markdownlint-cli
      - run: |
          markdownlint \
            --config ./.markdownlint.json \
            -i node_modules/** \
            -i build/** \
            -i dist/** \
            "README.md" "docs/**/*.md"
